server:
  port: 8081
  servlet:
    context-path: /web-demo

enable:
  swagger: true


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wpms_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: test
    password: test@123456