server:
  port: 8081
  servlet:
    context-path: /web-demo

spring:
  # datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: test
    password: test@123456

    # redis
    redis:
      database: 1
      host: localhost
      port: 6379
      password: test
      jedis:
        pool:
          max-active: 100
          max-idle: 8
          max-wait: -1



enable:
  swagger: true
