server:
  port: 8081
  servlet:
    context-path: /web-demo

spring:
  # datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql-connector-java 6 以前使用com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.181.13:3306/wpms_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: wpms_test
    password: wpms_test@123456
    # redis
    redis:
      database: 1
      host: localhost
      port: 6379
      password: test
      jedis:
        pool:
          max-active: 100
          max-idle: 8
          max-wait: -1
  # 上传文件大小设置
  servlet:
    multipart:
      # 单个文件大小限制10M
      max-file-size: 10MB
      # 单次请求限制30M
      max-request-size: 30MB

enable:
  swagger: true

# 自定义starter配置文件
com:
  liouxb:
    customPropertiesStr: first-starter

# MyBatis-plus
mybatis-plus:
  # 配置*.mapper.xml文件位置，不然找不到
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liouxb.web.demo.domain
  # 配置控制台打印完整带参数SQL语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  config: classpath:logback-spring.xml
  file:
    path: e:\logs\web-demo
  # 配置root级别，logback-spring.xml文件获取
  root:
    level: info
  # 配置相应目录下输入日志的级别
  level:
    com.liouxb.web.demo.service.impl: info
    com.liouxb.web.demo.mapper: debug
    java.sql: debug
    com.liouxb.web.demo.config.exception: error
